common_configs:
  experiment_name: batchnorm_no_norm_QMLP_sweep_weights
  artifact_directory: artifacts/chep
  wandb_project: chep_MetricLearning
  gpus: 1

  clear_directories: True

metric_learning_configs:
  # Dataset parameters
  input_dir: datasets/quickstart_example_1GeV
  output_dir: datasets/quickstart_metric_learning_processed
  pt_signal_cut: 1.
  pt_background_cut: 1.
  train_split: [80, 10, 10] # Number of [training, validation, testing] examples
  true_edges: modulewise_true_edges

  # Model parameters
  spatial_channels: 3 # 65 # 77
  cell_channels: 9 # 129 # 136
  emb_hidden: 512
  nb_layer: 4
  emb_dim: 12
  activation: ReLU
  weight: 2
  randomisation: 2
  points_per_batch: 100000
  r_train: 0.1
  r_val: 0.1
  r_test: 0.1
  knn: 50
  warmup: 8
  margin: 0.1
  lr: 0.001
  factor: 0.7
  patience: 4
  regime: [rp, hnm] #, norm]
  max_epochs: 180
  l1_loss: False
  l1_factor: 0.00005
  pruning_allow: False
  pruning_amount: 0.1
  pruning_freq: 200
  pruning_val_loss: 0.000002
  pruning_fn: "l1_unstructured"
 # pruning_fn: "ln_structured" 
 # pruning_dim: 0 # disconnect connections to one input; instead of disconnecting neurons (norm=0)
 # pruning_norm: 1
 # use_global_unstructured: False  # only for structured
  ##QNN Parameters
  quantized_network: True
  weight_bit_width_input: 8
  weight_bit_width_hidden: 8
  weight_bit_width_output: 8
  activation_qnn: True ## telling the network to use quantReLU()
  activation_bit_width_input: 7
  activation_bit_width_hidden: 5
  activation_bit_width_output: 6
  output_activation: False
  output_activation_quantization: False
  # Input quantization Parameters, only using fixed point representation
  input_quantization: True # also enables QuantIdentity
  integer_part: 2
  fractional_part: 10
  

gnn_configs:
  # Dataset parameters
  input_dir: datasets/quickstart_metric_learning_processed
  output_dir: datasets/quickstart_gnn_processed
  edge_cut: 0.5
  pt_signal_min: 1.
  pt_background_min: 1.
  datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
  datatype_split: [80, 10, 10] # Number of [training, validation, testing] examples
  noise: False

  # Model parameters
  spatial_channels: 3
  cell_channels: 0
  hidden: 128
  n_graph_iters: 6
  nb_node_layer: 3
  nb_edge_layer: 3
  layernorm: True
  aggregation: sum_max
  hidden_activation: SiLU
  weight: 2
  warmup: 10
  lr: 0.002
  factor: 0.7
  patience: 8
  truth_key: pid_signal
  regime: [pid]
  mask_background: True
  max_epochs: 20

track_building_configs:
  score_cut: 0.9
  output_dir: datasets/quickstart_track_building_processed

evaluation_configs:
  output_dir: datasets/quickstart_evaluation
  min_pt: 1
  max_eta: 4
  min_track_length: 3
  min_particle_length: 3
  matching_fraction: 0.5
  matching_style: ATLAS
